### ISSUE TITLE
lat_in ValueError: u should be between (0, pi)

### ISSUE THREAD

**Issue by oculus99** [hersfeldtn/koppenpasta#4]
With some datas, from latitudes made "lat_in" variable comes non-increasing order, then program crashes:

Retrieving Data...
Interpolating Data to Higher Resolution...
 Reticulating splines...
Traceback (most recent call last):
  File "/home/kitara/aphanerozimus1/labra2/koppenpasta.py", line 1836, in <module>
    MakeMap(in_files, output_name, cfg_loadname, land_type, sea_type, blend, color_type, col_list_path,
  File "/home/kitara/aphanerozimus1/labra2/koppenpasta.py", line 837, in MakeMap
    tas_spline = spint(lat_in,lon_in,tas_in)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kitara/anaconda3/lib/python3.11/site-packages/scipy/interpolate/_fitpack2.py", line 2313, in __init__
    raise ValueError('u should be between (0, pi)')
ValueError: u should be between (0, pi)

**Comment by hersfeldtn** [comment]
Interpolation has been rewritten in 2.0, should be generally more reliable in its handling of coordinates
